# Generated by Django 5.0.6 on 2024-06-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='username')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
            ],
        ),
    ]
