# Generated by Django 5.0.6 on 2024-06-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('age', models.SmallIntegerField(blank=True, default=0, verbose_name='年龄')),
                ('phone', models.IntegerField(blank=True, default=0, verbose_name='手机号码')),
                ('email', models.CharField(blank=True, default='', max_length=128, verbose_name='邮箱')),
                ('info', models.TextField(blank=True, default='', verbose_name='个人描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
