# Generated by Django 5.0.6 on 2024-06-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='手机号码'),
        ),
    ]
