# Generated by Django 5.0.6 on 2024-06-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0005_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('user', models.ManyToManyField(related_name='groups', to='orm_test.user')),
            ],
        ),
    ]
