# Generated by Django 5.0.6 on 2024-06-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0006_group'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='user',
            index_together={('username', 'phone')},
        ),
    ]
