# Generated by Django 5.0.6 on 2024-06-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0008_alter_diary_id_alter_group_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='手机号码'),
        ),
    ]
